from CaselessDict import caselessDict

LocPrefixes = ['san', 'los', 'santa', 'las', 'orange']

SFHoods = ['alamo square', 'nopa', 'bayview', 'bernal heights', 'castro', 
        'upper market', 'cole valley', 'ashbury hts', 'downtown', 'civic', 
        'van ness', 'excelsior', 'outer mission', 'financial district'
        'glen park', 'haight ashbury', 'hayes valley', 'ingleside', 
        'SFSU', 'CCSF', 'inner richmond', 'inner sunset', 'UCSF', 'laurel hts', 
        'presidio', 'lower haight', 'lower nob hill', 'lower pac hts', 'marina', 
        'cow hollow', 'mission district', 'nob hill', 'noe valley', 'north beach', 
        'telegraph hill', 'pacific heights', 'portola district',
        'potrero hill', 'richmond', 'seacliff', 'russian hill', 'SOMA', 
        'south beach', 'sunset', 'parkside', 'tenderloin', 'treasure island', 
        'twin peaks', 'diamond hts', 'USF', 'panhandle', 'visitacion valley',
        'west portal', 'forest hill', 'western addition', 'richmond', 'point', 
        'annex']

CLBayArea = caselessDict({
'San Fran' : 'San Francisco, CA',
'San Jose' : 'San Jose, CA',
'Berkeley' : 'Berkeley, CA',
'Oakland' : 'Oakland, CA',
'San Mateo' : 'San Mateo, CA',
'San Rafael' : 'San Rafael, CA',
'Sausalito' : 'Sausalito, CA',
'Larkspur' : 'Larkspur, CA',
'Santa Rosa' : 'Santa Rosa, CA',
'Marin' : 'Marin, CA',
'Sebastopol' : 'Sebastopol, CA',
'Healdsburg' : 'Healdsburg, CA',
'Petaluma' : 'Petaluma, CA',
'Novato' : 'Novato, CA',
'Mendocino': 'Mendocino, CA',
'Sonoma' : 'Sonoma, CA',
'Napa' : 'Napa Valley, CA',
'Monterey' : 'Monterey, CA',
'Santa Cruz' : 'Santa Cruz, CA',
'Los Gatos' : 'Los Gatos, CA',
'Morgan Hill' : 'Los Gatos, CA',
'Santa Clara' : 'Santa Clara, CA',
'Mountain View' : 'Mountain View, CA',
'Sunnyvale' : 'Sunnyvale, CA',
'Concord' : 'Concord, CA',
'Richmond' : 'Concord, CA',
'Alameda' : 'Alameda, CA',
'Albany' : 'Albany, CA',
'Brentwood' : 'Brentwood, CA',
'Danville' : 'Danville, CA',
'Vallejo': 'Vallejo, CA',
'Fairfield': 'Fairfield, CA',
'Pleasant Hill' : 'Pleasant Hill, CA',
'Walnut Creek' : 'Walnut Creek, CA',
'Martinez' : 'Martinez, CA',
'San Leandro' : 'San Leandro, CA',
'Fremont' : 'Fremont, CA',
'Hayward' : 'Hayward, CA',
'Union City' : 'Union City, CA',
'Newark' : 'Newark, CA',
'Capitola' : 'Capitola, CA',
'Aptos' : 'Aptos, CA',
'Boulder Creek' : 'Boulder Creek, CA',
'Livermore' : 'Livermore, CA',
'Pleasanton' : 'Pleasanton, CA',
'Alameda' : 'Alameda, CA',
'Dublin' : 'Dublin, CA',
'SF' : 'San Francisco, CA',
'S.F.' : 'San Francisco, CA',
'SJ' : 'San Jose, CA',
'S.J.' : 'San Jose, CA'}) #if not found, use barnacle hQ

CLDests =  caselessDict({
'Angeles' : 'Los Angeles, CA',
'Los Angeles' : 'Los Angeles, CA',
' LA ' : 'Los Angeles, CA',
'Long Beach' : 'Long Beach, CA',
'Sacramento' : 'Sacramento, CA',
'Stockton' : 'Stockton, CA',
'Fresno' : 'Fresno, CA',
'Grass Valley' : 'Grass Valley, CA',
'Scotts Valley' : 'Scotts Valley, CA',
'Soquel' : 'Soquel, CA',
'Watsonville' : 'Watsonville, CA',
'Harbin' : 'Harbin, CA',
'Bakersfield' : 'Bakersfield, CA',
'Eugene' : 'Eugene, OR',
'Portland' : 'Portland, OR',
'Seattle' : 'Seattle, WA',
'Ukiah' : 'Ukiah, CA',
'Arcata' : 'Arcata, CA', 
'Humboldt' : 'Humboldt, CA',
'Klamath' : 'Klamath, CA',
'Eureka' : 'Eureka, CA',
'Redding' : 'Redding, CA',
'Chico' : 'Chico, CA',
'Lake Tahoe' : 'Lake Tahoe, CA',
'Tahoe' : 'Lake Tahoe, CA',
'Yosemite' : 'Yosemite, CA',
'Reno' : 'Reno, NV',
'Barbara' : 'Santa Barbara, CA',
'Santa Barbara' : 'Santa Barbara, CA',
'Orange County' : 'Orange County, CA',
'San Luis Obispo' : 'San Luis Obispo, CA',
'Obispo' : 'San Luis Obispo, CA',
'Ventura' : 'Ventura, CA',
'Clarita' : 'Santa Clarita, CA',
'Santa Clarita' : 'Santa Clarita, CA',
'Monica' : 'Santa Monica, CA',
'Santa Monica' : 'Santa Monica, CA',
'Vegas' : 'Las Vegas, NV',
'Las Vegas' : 'Las Vegas, NV',
' LV ' : 'Las Vegas, NV',
'Ashland' : 'Ashland, OR',
'Medford' : 'Medford, OR',
'Diego' : 'San Diego, CA',
'San Diego' : 'San Diego, CA',
'Burbank' : 'Burbank, CA',
'Vancouver' : 'Vancouver, BC',
'L.A.' : 'Los Angeles, CA',
'Flagstaff' : 'Flagstaff, AZ',
'Phoenix' : 'Phoenix, AZ',
'Tuscon' : 'Tuscon, AZ',
'Santa Fe' : 'Santa Fe, NM',
'Albuquerque' : 'Albuquerque, NM',
'Austin' : 'Austin, TX'}) #if not found, send to mechanical turk


needy = ['need', 'looking for', 'wanted', 'stuck', 'carpool', 'shuttle', ' cab ', '?', 'seek']